theme: alembic-jekyll-theme

# Site settings
url: alembic-theme-test.netlify.com
baseurl: ''
title: 'Forestry & Alembic Test'
description: 'Testing out Forestry with Alembic for Jekyll, served with Netlify'
permalink: pretty

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Welcome: /
  About: /about/
  Blog: /blog/
  Fork Alembic: https://github.com/daviddarnes/alembic

#
navigation_footer:
  Myself: https://darn.es
  Netlify: https://www.netlify.com/
