# Set theme
theme: alembic-jekyll-theme

# Site settings
url: mydomain.com
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

# Footer nav
navigation_footer:
  Back to top: "#top"
